name: Pokemon Check Bot

on:
  push:
    branches: [ main ]
  schedule:
    # 8時間おき（日本時間の 0時, 8時, 16時 ごろ）
    - cron: '0 15,23,7 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml
      - name: Run script
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
        run: python main.py
